scrape_configs:
  - job_name: sonic_interfaces
    static_configs:
      - targets:
          - 100.105.8.4   # SONiC IP
    metrics_path: /snmp
    params:
      module: [sonic_if]
      auth: [public_v2]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 100.105.8.4:9116   # SNMP-EXPORTER IP ADDR

  - job_name: sonic_system
    static_configs:
      - targets: [100.105.8.4]
    metrics_path: /snmp
    params:
      module: [sonic_system]
      auth: [public_v2]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 100.105.8.4:9116

  - job_name: sonic_sensors
    static_configs:
      - targets: [100.105.8.4]
    metrics_path: /snmp
    params:
      module: [sonic_sensors]
      auth: [public_v2]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 100.105.8.4:9116

  - job_name: sonic_routing
    static_configs:
      - targets: [100.105.8.4]
    metrics_path: /snmp
    params:
      module: [sonic_routing]
      auth: [public_v2]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 100.105.8.4:9116
